repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
    - id: check-ast
    - id: check-builtin-literals
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: check-byte-order-marker
    - id: check-merge-conflict
    - id: check-symlinks
    - id: detect-private-key
    - id: check-yaml
      args: [--unsafe]
    - id: check-toml

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.12
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.11.4'
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      types_or: [python, jupyter]
    - id: ruff-format
      types_or: [python, jupyter]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    - id: mypy
      entry: python3 -m mypy --config-file pyproject.toml
      language: system
      types: [python]
      exclude: "tests"

  - repo: https://github.com/crate-ci/typos
    rev: v1  # v1.19.0
    hooks:
      - id: typos
        args: []

ci:
    autofix_commit_msg: |
        [pre-commit.ci] Add auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: [pytest,doctest,mypy]
    submodules: false
